name: humann_regroup
description: Regrouping genes to other functional categories
keywords:
  - function
  - metagenomics
  - metatranscriptomics
  - profiling
  - community
tools:
  - humann:
      description: "HUMAnN: The HMP Unified Metabolic Analysis Network, version 3"
      homepage: http://huttenhower.sph.harvard.edu/humann
      documentation: https://github.com/biobakery/biobakery/wiki/humann3
      tool_dev_url: https://github.com/biobakery/humann
      doi: "10.7554/eLife.65088"
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: file
      description: Tab separated abundance file of HUMAnN3
      pattern: "*.{tsv.gz,tsv}"
  - groups:
      type: value
      description: Regroup abundance values to MetaCyc reaction (RXN) abundances
      pattern: "{uniref90_rxn,uniref50_rxn}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - regroup:
      type: file
      description: Re-grouped compressed tab separated text file
      pattern: "*.{tsv.gz}"

authors:
  - "@d4straub"
